#!/usr/bin/python

import cgi 

#import cgitb; cgitb.enable()

import os, sys, time, json, getopt
import RPi.GPIO as GPIO

print("Content-Type: application/json\n\n")
rn = "\r\n";
data = json.loads(sys.stdin.read())
action = data.get("action")
pumpId = data.get("pumpId")
during = int(data.get("during"))

print(action)
print(pumpId)
print(during)

pumps = {}
pumps["pump1"] = 17
pumps["pump2"] = 18
pumps["pump3"] = 27
pumps["pump4"] = 22
pumps["pump5"] = 23
pumps["pump6"] = 24
pumps["pump7"] = 25
pumps["pump8"] = 4

#action = "start" 
#pumpId = "pump1"
#during = 1

gpioId = pumps.get(pumpId)

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(gpioId, GPIO.OUT)
GPIO.output(gpioId, GPIO.LOW)
GPIO.output(gpioId, GPIO.HIGH)

#os.system("gpio read "+str(gpioId))

print 'action: {} \r\n gpioId: {} \r\n during: {}'.format(action, gpioId, during)

time.sleep(during)

GPIO.output(gpioId, GPIO.LOW)

GPIO.cleanup()
