#!/usr/bin/python

import cgi 

#import cgitb; cgitb.enable()

import os, sys, time, json, getopt
import RPi.GPIO as GPIO


rn = "\r\n";

pumpId = sys.argv[1]
during = sys.argv[2]

print(pumpId)
print(during)

#pumps = {}
#pumps["pump1"] = 17
#pumps["pump2"] = 18
#pumps["pump3"] = 27
#pumps["pump4"] = 22
#pumps["pump5"] = 23
#pumps["pump6"] = 24
#pumps["pump7"] = 25
#pumps["pump8"] = 4

gpioId = pumpId

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(gpioId, GPIO.OUT)
GPIO.output(gpioId, GPIO.LOW)
GPIO.output(gpioId, GPIO.HIGH)

#os.system("gpio read "+str(gpioId))

print 'gpioId: {} \r\n during: {}'.format(gpioId, during)

time.sleep(during)

GPIO.output(gpioId, GPIO.LOW)

GPIO.cleanup()
